language: r
os:
    - linux
r:
    - release
cache: packages
sudo: false

script:
    - R CMD build .
    - R CMD check *tar.gz
    - R CMD INSTALL *tar.gz
    - Rscript ./tests/testthat/tests1.R
r_packages:
    - covr

after_success:
    - Rscript -e 'library(covr); codecov'