language: r
os:
    - linux
    - osx
r:
    - release
cache: packages
sudo: false

before_install:
    - chmod 755 ./test_runner.sh

script:
    - R CMD build .
    - R CMD check *tar.gz
    - Rscript ./tests/testthat/tests1.R
